### ISSUE TITLE
Hex color support in messages.yml (preferably MiniMessage implementation)

### ISSUE THREAD

**Issue by SpeastTV** [srnyx/limited-lives#21]
### What and How?

Hex color (aka. rgb) support, preferably a MiniMessage implementation in messages.yml.
![image](https://github.com/srnyx/limited-lives/assets/106100330/42313435-be27-4f73-9d6b-a688260ed1ed)

### Why?

Because hex colors are the new way to go, they are much more customizable and not limited to the vanilla colors (e.g. &a).
Also, if you use MiniMessage to implement hex colors, it would have other benefits besides hex colors.

### Are there alternatives?

Another way, instead of MiniMessage, to implement hex colors.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by SpeastTV** [comment]
Or is there, by any chance, a way to use hex colors with the already implemented JSON? --> https://github.com/srnyx/annoying-api/wiki/messages-file

**Comment by srnyx** [comment]
**Regarding hex codes:**
You can use `&x&f&f&f&f&f&f`, `ffffff` being the hex code (so `&x` and then the hex code with `&` before each character). It's a bit annoying, but all I can offer right now

**Regarding MiniMessage support:**
Track https://github.com/srnyx/annoying-api/issues/6 for MiniMessage support, as my API is what handles the messages files for all my plugins. [I've attempted support before](https://github.com/srnyx/annoying-api/tree/adventure), but it didn't go well, and I'm not really sure if I'll ever add support for it. I experienced issues with PlaceholderAPI and my own placeholders.

Closing this as a "duplicate" so that I only have to worry about the issue on the API's GitHub.
