### ISSUE TITLE
Replace "x is an invalid argument" when trying to give someone more lives then the limit.

### ISSUE THREAD

**Issue by Luis2000yt** [srnyx/limited-lives#22]
### What and How?

Title pretty much says it all, instead of it showing the text in the image, and failing, have it give them the max amount possible and also state that
![image](https://github.com/user-attachments/assets/22a0b8a7-f5cf-414d-a13f-152008991da9)

### Why?

Quality of life using the Plugin

### Are there alternatives?

make it say how many you can add max instead of just failing ig?

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by srnyx** [comment]
I think I originally had it give the max possible, but I thought it would be too confusing/unexpected for players.
Like if I want to give my friend 3 lives, I expect them to get 3 lives, not 1 or 2 lives (because they hit the max).
However, I can see why it's also better to have it just give the max because that's more convenient and the issue I'm arguing is not a concern for everyone.
Maybe I can make it a config option (`give-as-many-possible`) or something, but probably not as I'll most likely just improve the error messages to resolve it.

In regards to the messages, I think I was just lazy and made it send the same message for any sort of failure because that was easier and I didn't deem it pressing enough to have to have a complicated system to detect the type of failure that occurred (not enough lives, other player has max lives, some sort of failure with data, etc...).
But since you've brought it up, I will look more into improving the messages so they reflect the error better.

Sorry for the lengthy response hahah
